### ISSUE TITLE
Does anyone want to maintain this gem?

### ISSUE THREAD

**Issue by calavera** [chef/minitest-chef-handler#87]
I haven't use this gem in years. It looks like there are a lot of people using it and I'm not a knowledgeable person to maintain it anymore. If you use this gem very frequently and are willing to maintain it let me know. I'll transfer ownership of the repo to your user or organization of choice.

![image](https://cloud.githubusercontent.com/assets/1050/6032616/0ab4d74e-abc0-11e4-9440-699eb57cf2b7.png)

**Comment by fujin** [comment]
@btm maintains the cookbook, I'm sure he would consider maintaining the gem too. The download counter for cookbooks on the supermarket is actually bugged (super over-inflated) so that is not an accurate user figure.

**Comment by btm** [comment]
I wrote up the cookbook one night in a hotel as a proof on concept and a bunch of people started using it. The internet is crazy. @dpetzel was the most recent one doing work on the cookbook. I presume people are still using it. Anyway, I'm happy to manage the gem, although I'm unlikely to do much coding on it myself.

**Comment by damm** [comment]
Transfer it to an organization and let people help?

**Comment by lamont-granquist** [comment]
If you want to add me and fnichol as maintainers for the gem and for rubygems we could at least keep it going on life support.  I use my personal lamont@scriptkiddie.org e-mail on rubygems, and fletcher is fnichol@nichol.ca on rubygems.

**Comment by btm** [comment]
@calavera Could you transfer this repo to the Chef GitHub organization and add @lamont-granquist and @fnichol to the gem?

**Comment by calavera** [comment]
Thank you guys!

It looks like I cannot transfer it to Chef because I don't have admin rights there. I already added Lamont and Fletcher to rubygems. I can transfer the repo to one of you and you can transfer it to the org if you have admin privileges in Chef.

**Comment by btm** [comment]
@calavera Transfer it to me and I'll take care of it. Thanks!

**Comment by calavera** [comment]
@btm it looks like you need to remove your fork first :pensive:

**Comment by btm** [comment]
@calavera done.

**Comment by calavera** [comment]
@btm transfer requested! :tada:

**Comment by btm** [comment]
Great. This is now https://github.com/chef/minitest-chef-handler. I'm not privy to @lamont-granquist's plans but we're good to go on them whatever they were. :)

**Comment by lamont-granquist** [comment]
Heh, actually i don't have too many plans.  Ideally I'd like to see this back in community hands, but at least now I can do releases when I make changes in stuff in chef-client that breaks things.  Would not be very surprised at all if jkeiser's resource changes wind up breaking stuff here as well.

**Comment by calavera** [comment]
thank you again guys, I'm very happy about all this! :heart:

**Comment by lamont-granquist** [comment]
although with the stuff that @jkeiser wants to do with resources being able to report their internal state, we may wind up wanting to rip out some of what this gem does with poking around internally into  resources to load state, and there may be a way to create generic matchers for chef-client that can be both loaded into minitest (as minitest-chef-handler v2 maybe) or loaded into rspec as a more native-chef alternative to serverspec...   hmmmmm....

**Comment by btm** [comment]
@lamont-granquist yeah, I'm not sure how popular minitest-handler will be long term, but with no one else piping up we can do a little.

@chef/client-windows with test-kitchen working on Windows now, should we go through and make a pass at getting minitest working on Windows? There's a number of issues filed here. Is there any value here compared to [pester](a00abc7c22e9ff001bca2600038afbec275b148a)? Cross-platform?
