### ISSUE TITLE
Does not install on Windows 2008R2 with Ruby version < 2.0.0, Chef < 12

### ISSUE THREAD

**Issue by heathsnow** [chef/minitest-chef-handler#88]
This broke last week for Windows nodes running any Ruby version < 2.0.0.

I'm running:
* Chef 11.12.4
* Ruby 1.9.3
* Windows 2008R2

During chef-client run:
```
==> windows: Gem::DependencyError
==> windows: --------------------
==> windows: Unable to resolve dependencies: mixlib-shellout requires win32-process (~> 0.7.5), windows-pr (~> 1.2.4)
```
Both Ohai and Mixlib-Shellout had new releases last week.  When attempting to install minitest-chef-handler gem:

```
C:\Users\Administrator>ver

Microsoft Windows [Version 6.1.7600]

C:\Users\Administrator>chef-client -v
Chef: 11.12.4

C:\Users\Administrator> ruby -v
ruby 1.9.3p484 (2013-11-22) [i386-mingw32]

C:\Users\Administrator>gem install minitest-chef-handler
ERROR:  While executing gem . . . (Gem::DependencyError)
    Unable to resolve dependencies: mixlib-shellout requires win32-process (~) 0.7.5), windows-pr (~) 1.2.4)
```

**Comment by heathsnow** [comment]
Additional information:

If I install windows-pr (latest) and win32-process-0.7.5 and try to gem install minitest-chef-handler I get this error:
```
ERROR:  Error installing minitest-chef-handler:
        ohai requires Ruby version >= 2.0.0
```

**Comment by heathsnow** [comment]
I was able to install the minitest-chef-handler gem by forking it and locking the chef dependency to ~> 11.0.0.  I'm not sure how this should be fixed for the community.  Maybe do that for one version and then release another version without that constraint?  Then just direct Chef 11 users to this version and Chef 12 users to the other.

Thoughts?

**Comment by dpetzel** [comment]
We've bumped into this as well this week. We've been able to work around it by first installing mixlib-shellout version `2.0.1` which is the version just prior to the the current (`2.1.0`) which was released on May 19th. Installation of this Gem seem be failing since that date for us.

II'm also not sure what the fix is...

**Comment by dpetzel** [comment]
I'm wondering if this wasn't fixed (directly or indirectly) by https://github.com/chef/minitest-chef-handler/commit/566346d068fd98f943fc1d6c7bf6701029ef7228. Looking through the dependency tree it appears its trying to pull in Chef 12 and Ohai 8. @lamont-granquist switch of Chef to a dev dependency might work around this issue.

Wondering if the fix here is simply a new release of this gem to catch those dependency changes....

**Comment by dpetzel** [comment]
@lamont-granquist what are the chances you could cut a build from master? We've been doing some testing and it seems that whats there solves this issue.

**Comment by lamont-granquist** [comment]
Pushed a new release a few minutes ago.
